# These are supported funding model platforms

github:  [wai4043 , zweminthu, WaiLinn-Oo, kaungkhantkyaw199]
patreon: user?u=30239012
tidelift: maven/Team-3-DevOps
custom: "https://github.com/Team-3-DevOps/coursework.git"
