sudo: required

language: java

services:
  - docker

after_success:
  - docker network create --driver bridge se-methods
  - docker pull mongo
  - docker run -d --name mongo-dbserver --network Coursework mongo
  - docker build -t Coursework .
  - docker run --network Coursework Coursework