@startuml

actor user as "The user"

rectangle Database

rectangle "Population accessibility function" {


    usecase world as "Choose world"
    usecase continent as "Choose continent"
    usecase region as "Choose region"
    usecase country as "Choose country"
    usecase district as "Choose district"
    usecase city as "Choose city"
    usecase cc as "Choose category"
    usecase edit as "Edit the population
    of the chosen place"

    user -- cc
    user -- edit
    cc <.. world : include
    cc <.. continent : include
    cc <.. region : include
    cc <.. country : include
    cc <.. district : include
    cc <.. city : include

    edit -- Database
    cc -- Database



}

@enduml